name: Analyze (stable)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Log Dart/Flutter versions
        run: |
          dart --version
          flutter --version
      - name: Prepare dependencies
        run: flutter pub get
      - name: Analyse the repo
        run: flutter analyze lib example/lib
     - name: Run tests
       run: flutter test
      - name: Generate docs
        run: |
          dart pub global activate dartdoc
          dart pub global run dartdoc .
